Repository toptal/simple-react-calendar, pull requests merged in 2020-02, with the labels that each got.

#127 fix(ci): fix semantic release
  .circleci/config.yml
  bin/bump-package-json
  bin/utils/index.js
  config/_ci/release/bump-package-json
  config/_ci/release/bump-version
  config/_ci/release/prepare-assets
  package.json
  release.config.js
  yarn.lock
Labels: bug

#128 fix(ci): disable storybook deploy to check the whole process
  .circleci/config.yml
Labels: bug

#130 fix(ci): fix semantic versioning
  bin/bump-package-json
  bin/utils/index.js
  release.config.js
Labels: bug

#131 fix(ci): turn on storybook generate
  .circleci/config.yml
  package.json
  release.config.js
  yarn.lock
Labels: bug

#132 fix(ci): turn off storybook deployment
  .circleci/config.yml
Labels: bug

#118 tests(day): rewrite tests with RTL
  config/_jest/setupAfterEnv.ts
  jest.config.js
  package.json
  src/calendar/__specs__/__snapshots__/day_spec.tsx.snap
  src/calendar/__specs__/day_spec.tsx
  src/calendar/day.tsx
  yarn.lock
Labels: enhancement

#133 chore(eslint): apply eslint and prettier company standard
  .circleci/config.yml
  .eslintignore
  .eslintrc.js
  .prettierignore
  .prettierrc
  .prettierrc.js
  config/_ci/danger/plugins/empty-assignee/index.ts
  config/_ci/danger/plugins/empty-labels/index.ts
  config/_jest/setupTests.js
  config/webpack.core.js
  config/webpack.dev.js
  config/webpack.lib.js
  jest.config.js
  package.json
  src/@types/index.ts
  src/calendar/__specs__/calendar_spec.tsx
  src/calendar/__specs__/day_spec.tsx
  src/calendar/__specs__/days_of_week_spec.tsx
  src/calendar/__specs__/header_button_spec.tsx
  src/calendar/__specs__/month_header_spec.tsx
  src/calendar/__specs__/month_spec.tsx
  src/calendar/__specs__/notice_spec.tsx
  src/calendar/__specs__/week_spec.tsx
  src/calendar/calendar.tsx
  src/calendar/day.tsx
  src/calendar/day_of_week.tsx
  src/calendar/days_of_week.tsx
  src/calendar/header_button.tsx
  src/calendar/month.tsx
  src/calendar/month_header.tsx
  src/calendar/stories/index.jsx
  src/calendar/week.tsx
  src/example/app.tsx
  yarn.lock
Labels: chore

#134 chore(npm): remove prepare commmand
  package.json
Labels: enhancement

#135 feat(day): isolate logic and render prop on the day level
  src/@types/index.ts
  src/RenderPropsComponents/Day/Day.tsx
  src/RenderPropsComponents/Day/index.ts
  src/RenderPropsComponents/Day/test.tsx
  src/calendar/__specs__/__snapshots__/calendar_spec.tsx.snap
  src/calendar/__specs__/__snapshots__/day_spec.tsx.snap
  src/calendar/__specs__/__snapshots__/week_spec.tsx.snap
  src/calendar/__specs__/month_spec.tsx
  src/calendar/__specs__/week_spec.tsx
  src/calendar/calendar.tsx
  src/calendar/day.tsx
  src/calendar/month.tsx
  src/calendar/week.tsx
  src/example/app.tsx
  src/example/style/base_style.styl
  src/example/style/date_picker.styl
  src/helper/index.ts
  src/helper/test.ts
Labels: enhancement
