Repository toptal/simple-react-calendar, pull requests merged in 2020-03, with the labels that each got.

#139 chore(package): update davinci & prettier
  .babelrc.js
  .circleci/config.yml
  .eslintrc.js
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/issue_template.md
  .storybook/config.js
  .storybook/preview-head.html
  .storybook/webpack.config.js
  CHANGELOG.md
  README.md
  package.json
  release.config.js
  src/calendar/calendar.tsx
  src/calendar/month.tsx
  yarn.lock
Labels: chore, dependencies

#138 refactor: move DayOfWeek to render props components
  jest.config.js
  package.json
  src/@types/index.ts
  src/RenderPropsComponents/Day/__snapshots__/test.tsx.snap
  src/RenderPropsComponents/DayOfWeek/DayOfWeek.tsx
  src/RenderPropsComponents/DayOfWeek/__snapshots__/test.tsx.snap
  src/RenderPropsComponents/DayOfWeek/index.tsx
  src/RenderPropsComponents/DayOfWeek/test.tsx
  src/calendar/__specs__/days_of_week_spec.tsx
  src/calendar/calendar.tsx
  src/calendar/day_of_week.tsx
  src/calendar/days_of_week.tsx
  src/calendar/month.tsx
Labels: fc-rewrite

#141 feat(notice): recreate notice component with a render prop approach
  README.md
  src/@types/index.ts
  src/RenderPropsComponents/Notice/Notice.tsx
  src/RenderPropsComponents/Notice/__snapshots__/test.tsx.snap
  src/RenderPropsComponents/Notice/index.tsx
  src/RenderPropsComponents/Notice/test.tsx
  src/calendar/__specs__/__snapshots__/notice_spec.tsx.snap
  src/calendar/__specs__/notice_spec.tsx
  src/calendar/calendar.tsx
  src/calendar/month.tsx
  src/calendar/notice.tsx
  src/helper/index.ts
Labels: enhancement
