Repository toptal/simple-react-calendar, pull requests merged in 2020-07, with the labels that each got.

#216 fix: remove unsafe warning
  src/calendar/calendar.tsx
Labels: enhancement

#214 fix: render props rework
  package.json
  src/@types/index.ts
  src/RenderPropsComponents/DayOfWeek/index.ts
  src/RenderPropsComponents/DaysOfWeek/DaysOfWeek.tsx
  src/RenderPropsComponents/DaysOfWeek/__snapshots__/test.tsx.snap
  src/RenderPropsComponents/DaysOfWeek/index.ts
  src/RenderPropsComponents/DaysOfWeek/test.tsx
  src/RenderPropsComponents/HeaderButton/HeaderButton.tsx
  src/RenderPropsComponents/HeaderButton/__snapshots__/test.tsx.snap
  src/RenderPropsComponents/HeaderButton/index.ts
  src/RenderPropsComponents/HeaderButton/test.tsx
  src/RenderPropsComponents/Month/Month.tsx
  src/RenderPropsComponents/Month/__snapshots__/test.tsx.snap
  src/RenderPropsComponents/Month/index.ts
  src/RenderPropsComponents/Month/test.tsx
  src/RenderPropsComponents/MonthHeader/MonthHeader.tsx
  src/RenderPropsComponents/MonthHeader/__snapshots__/test.tsx.snap
  src/RenderPropsComponents/MonthHeader/index.ts
  src/RenderPropsComponents/MonthHeader/test.tsx
  src/RenderPropsComponents/Notice/test.tsx
  src/RenderPropsComponents/Week/Week.tsx
  src/RenderPropsComponents/Week/__snapshots__/test.tsx.snap
  src/RenderPropsComponents/Week/index.ts
  src/RenderPropsComponents/Week/test.tsx
  src/calendar/__specs__/__snapshots__/month_spec.tsx.snap
  src/calendar/calendar.tsx
  yarn.lock
Labels: typescript-migration

#225 fix(dev): update packages and fix commit lint
  package.json
  src/RenderPropsComponents/Month/Month.tsx
  src/RenderPropsComponents/Week/Week.tsx
  src/calendar/calendar.tsx
  yarn.lock
Labels: bug

#226 fix(circleci): filter master triggered PR job
  .circleci/config.yml
Labels: bug
